import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/lib/contexts/theme-context";
import { AuthProvider } from "@/lib/contexts/auth-context";

const iranSansX = localFont({
  src: [
    {
      path: "./fonts/IRANSansX-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/IRANSansX-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/IRANSansX-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-iransansx",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${iranSansX.variable} h-full`}>
      <body className="h-full font-sans antialiased">
        <ThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
